// Copyright 2025 the Fearless_SIMD Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! A module containing generated files
//!
//! All files in this subdirectory are autogenerated by the `fearless_simd_gen` crate.

#[cfg(target_arch = "aarch64")]
mod neon;
#[cfg(target_arch = "wasm32")]
mod wasm32;

mod ops;
mod simd_trait;
mod simd_types;

#[cfg(target_arch = "aarch64")]
pub use neon::*;
#[cfg(target_arch = "wasm32")]
pub use wasm32::*;

pub use simd_trait::*;
pub use simd_types::*;
